### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by 2311091775** [selvachandrasekaranselvaraj/GNN_prediction#1]
python graphs.py
Number of graphs in ../graphs/graphs_gnn_cubic.pkl: 1
Number of graphs in ../graphs/graphs_gnn_hexagonal.pkl: 1
Number of graphs in ../graphs/graphs_gnn_trigonal.pkl: 1
Number of graphs in ../graphs/graphs_gnn_tetragonal.pkl: 1
Number of graphs in ../graphs/graphs_gnn_orthorhombic.pkl: 1
Number of graphs in ../graphs/graphs_gnn_monoclinic.pkl: 1
Number of graphs in ../graphs/graphs_gnn_triclinic.pkl: 1
Original number of graphs: 7
Traceback (most recent call last):
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/LHF/GNN_prediction/train/graphs.py", line 137, in <module>
    main()
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/LHF/GNN_prediction/train/graphs.py", line 124, in main
    y_values_dict, graphs = process_graphs()
                            ^^^^^^^^^^^^^^^^
  File "/media/ubuntu/cdb918a9-e3b3-40a1-bf0e-97b8b44001ca/LHF/GNN_prediction/train/graphs.py", line 118, in process_graphs
    value = g['y_values'][i]
            ~^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
![544c1b82ea8f5b844f4a867c023e3147](https://github.com/user-attachments/assets/6cf3f12e-00d5-4919-8256-9a46c05cce4f)
Ask for help。I wonder what this y_values means？Because it always raises that question。

**Comment by selvachandrasekaranselvaraj** [comment]
Hi,
y_values are the properties of materials let's say 'V'-volume, 'n'-number of sites, 'p'-density.... and so on as I mentioned in plot_labels.

These values are in ./graphs/graphs_gnn_cubic.pkl.... 
I did not upload these pickle file because of its size. You can download them using this file: ./structures/structures.py

**Comment by 2311091775** [comment]
> Hi, y_values are the properties of materials let's say 'V'-volume, 'n'-number of sites, 'p'-density.... and so on as I mentioned in plot_labels.
> 
> These values are in ./graphs/graphs_gnn_cubic.pkl.... I did not upload these pickle file because of its size. You can download them using this file: ./structures/structures.py

Thank you for help.I used this file ./structures/structures.py to download it  and put it into this folder。But I think the variable “g” is a List not a Dict. So I still dont konw how to modify the code "value = g["y_values"][i]" .Can you make an example here.Thank you so much.
![b210988c810529dd64685bf027d543f6](https://github.com/user-attachments/assets/0d919994-9b08-40d7-9d8e-2e32f20b0743)
